server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql.coffit.today:3306/dasi
    url: jdbc:mysql://localhost/dasi
    username: root # HIkdt6
    password: 1234 # HIkdt6

  mvc:
    view:
      suffix: .html

mybatis:
  mapper-locations: mappers/**/*.xml

