server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql.coffit.today:3306/dasi
    url: jdbc:mysql://localhost:3306/dasi
    username: root # HIkdt6
    password: 1234 # HIkdt6

  mvc:
    view:
      suffix: .html

mybatis:
  mapper-locations: mappers/**/*.xml

pagehelper:
  helper-dialect: mysql
  auto-dialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true